### PR TITLE
Initial application setup [WIP]

### PR DESCRIPTION
**Pull request by iamonuwa**
- [ ] All speced functionaly works
- [ ] Unit tests for all functions and modules
- [ ] Integration tests for all use cases
- [ ] Comment documentation for all modules, functions and types
- [x] Ready for code review

### CODE REVIEW

**Comment by avive** [comment]
Good start! Let's please merge once running on iOS works and Electron initial setup is in for desktop. I'm having trouble running on iOS and Android simulators. On iOS I get 'app cosmic has not been registered error' when running `yarn iOS` from the project root folder...

**Comment by iamonuwa** [comment]
Thank you @avive. I and Samuel are currently working on it. We'll update the issues

**Comment by avive** [comment]
not working as this is still wip...

**Comment by avive** [comment]
not merging since this is still wip...

**Pull request merged**
